# A compose file to bring up loki for testing
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.7.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
